
apiVersion: shyrkaio.github.io/v1alpha3
kind: Hypnos
metadata:
  name: test-012
  labels:
    io.shyrka.erebus/hypnos: "sample012"
    io.shyrka.erebus/role: "test"
  annotations:
    io.shyrkaio.github.erebus/hypnos: "{}"
spec:
  namespaceTargetedLabel: "io.shyrka.erebus/hypnos=sample012"
  targetedLabel: "io.shyrka.erebus/hypnos=sample"
  resourceType:
    - "Deployment"
  # this is for testing regular cron should be
  wakeup-cron: "0/5 * * * *"
  sleep-cron:  "0/2 * * * *"

  #not-implemented-yet
  load-policy: no-action #not-implemented-yet
  dry-run: false
  pause: false #not-implemented-yet
  comments: "Start/stop several Deployments correctly labelled in a namespace correctly labelled  every 5 and 2 minutes"