apiVersion: v1
kind: Namespace
metadata:
  name: hypnos-smp-080
  labels:
    app: hypnos-080
    io.shyrka.erebus/hypnos: "sample080"
    io.shyrka.erebus/role: "test"
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.shyrka.erebus/hypnos: "sample"
    io.shyrka.erebus/role: "test"
    app: hypnos-080
  name: hypnos-080
  namespace: hypnos-smp-080
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    app: hypnos-080
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hypnos-080
    spec:
      containers:
        - image: quay.io/kanedafromparis/nginx:ocp-0.3
          imagePullPolicy: IfNotPresent
          name: hypnos-080
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange

